name: Deploy to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'package.json'
      - 'yarn.lock'
      - 'dist'
      - 'node_modules'
      - '.github'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          yarn
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: watermark.yycc.dev
          publish_branch: gh-pages
          enable_jekyll: false
          keep_files: false
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
